# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginWindow(object):

    def setupUi(self, loginWindow):
        loginWindow.setObjectName("loginWindow")
        loginWindow.resize(383, 210)
        self.centralwidget = QtWidgets.QWidget(loginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.denglu = QtWidgets.QPushButton(self.centralwidget)
        self.denglu.setGeometry(QtCore.QRect(120, 150, 121, 31))
        self.denglu.setObjectName("denglu")
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(160, 50, 113, 20))
        self.name.setObjectName("name")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(160, 90, 113, 20))
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 50, 54, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 90, 54, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 10, 121, 31))
        self.label_3.setObjectName("label_3")
        self.waring = QtWidgets.QLabel(self.centralwidget)
        self.waring.setEnabled(True)
        self.waring.setGeometry(QtCore.QRect(100, 120, 181, 20))
        self.waring.setAutoFillBackground(False)
        self.waring.setObjectName("waring")
        loginWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(loginWindow)
        self.statusbar.setObjectName("statusbar")
        loginWindow.setStatusBar(self.statusbar)

        self.retranslateUi(loginWindow)
        QtCore.QMetaObject.connectSlotsByName(loginWindow)


    def retranslateUi(self, loginWindow):
        _translate = QtCore.QCoreApplication.translate
        loginWindow.setWindowTitle(_translate("loginWindow", "登录"))
        self.denglu.setText(_translate("loginWindow", "登录"))
        self.name.setPlaceholderText(_translate("loginWindow", "请输入账号"))
        self.password.setPlaceholderText(_translate("loginWindow", "请输入密码"))
        self.label.setText(_translate("loginWindow", "账号"))
        self.label_2.setText(_translate("loginWindow", "密码"))
        self.label_3.setText(_translate("loginWindow", "欢迎使用Talknet"))
        self.waring.setText(_translate("loginWindow", "用户名或密码错误，请重试！"))
